-- Runtime for generated ACE .ace_test groups.
-- Maintainers do not edit this file; it owns native fixture creation, actions, observations,
-- assertions, and cleanup underneath the maintainer-facing DSL.

local Runtime = {}
-- These Entity-meta shims stand in for missing player/toolgun methods only in
-- headless fixtures; real Player meta methods still take precedence for players.
local HeadlessOwnershipShims = {
	CPPISetOwner = function(entity, owner) entity._TestCPPIOwner = owner end,
	CPPIGetOwner = function(entity) return entity._TestCPPIOwner end,
	UniqueID = function(entity) return "ACE_HEADLESS_" .. entity:EntIndex() end,
	CheckLimit = function() return true end,
	AddCount = function() end,
	AddCleanup = function() end,
	GetInfo = function() return "0" end,
	GetInfoNum = function(_, _, default) return default or 0 end,
	Nick = function() return "ACE headless owner" end,
	SteamID64 = function() return "0" end,
}

local function ensureHeadlessOwnership(State)
	if type(FindMetaTable) ~= "function" then return end
	local EntityMeta = FindMetaTable("Entity")
	if not EntityMeta then return end
	State.HeadlessOwnershipInstalled = State.HeadlessOwnershipInstalled or {}
	for Name, Shim in pairs(HeadlessOwnershipShims) do
		if not EntityMeta[Name] then
			EntityMeta[Name] = Shim
			State.HeadlessOwnershipInstalled[Name] = true
		end
	end
end

local function restoreHeadlessOwnership(State)
	if not State or not State.HeadlessOwnershipInstalled then return end
	if type(FindMetaTable) ~= "function" then
		State.HeadlessOwnershipInstalled = nil
		return
	end
	local EntityMeta = FindMetaTable("Entity")
	if EntityMeta then
		for Name in pairs(State.HeadlessOwnershipInstalled) do EntityMeta[Name] = nil end
	end
	State.HeadlessOwnershipInstalled = nil
end

local function overrideMethod(State, Ent, Name, Callback)
	local Meta = FindMetaTable("Entity")
	State.MethodOverrides[Name] = State.MethodOverrides[Name] or {}
	State.MethodOriginals[Name] = State.MethodOriginals[Name] or Meta[Name]
	State.MethodOverrides[Name][Ent] = Callback
	if State.MethodInstalled[Name] then return end
	local Original = State.MethodOriginals[Name]
	Meta[Name] = function(self, ...)
		local Override = State.MethodOverrides[Name][self]
		if Override then return Override(self, ...) end
		return Original(self, ...)
	end
	State.MethodInstalled[Name] = true
end

local function track(State, Ent)
	if IsValid(Ent) then
		State.Entities[#State.Entities + 1] = Ent
	end
	return Ent
end

local function fixture(State, Name, Definitions)
	local Definition = Definitions and Definitions[Name]
	if not Definition or Definition.invalid then return nil end
	if Definition.kind == "value" then
		return istable(Definition.value) and table.Copy(Definition.value) or Definition.value
	end

	local Ent
	local SpawnClass = Definition.spawnClass or Definition.class or "prop_physics"
	if Definition.physics == "invalid" then
		Ent = track(State, ents.Create(SpawnClass))
		if not IsValid(Ent) then return end
		Ent:SetModel(Definition.model or "models/props_junk/wood_crate001a.mdl")
	else
		Ent = track(State, ents.Create(SpawnClass))
		if not IsValid(Ent) then return end
		Ent:SetModel(Definition.model or "models/props_junk/wood_crate001a.mdl")
		Ent:Spawn()
	end
	if not Ent then return end
	if Ent.Activate then Ent:Activate() end
	local Phys = Ent:GetPhysicsObject()
	if IsValid(Phys) then
		if Phys.SetMass then Phys:SetMass(Definition.mass or 10) end
		if Phys.Wake then Phys:Wake() end
	end

	if Definition.kind == "native_player" then
		overrideMethod(State, Ent, "IsPlayer", function() return true end)
	elseif Definition.kind == "native_vehicle" then
		overrideMethod(State, Ent, "IsVehicle", function() return true end)
	end
	if Definition.class and Definition.class ~= "prop_physics" then
		local Class = Definition.class
		overrideMethod(State, Ent, "GetClass", function() return Class end)
	end
	if Definition.ignoredClass then
		local Class = Definition.ignoredClass
		overrideMethod(State, Ent, "GetClass", function() return Class end)
	end
	if Definition.exploding then Ent.Exploding = true end
	if Definition.ace then
		Ent.ACE = Ent.ACE or {}
		for Key, Value in pairs(Definition.ace) do Ent.ACE[Key] = Value end
	end
	if Definition.name then
		Ent.ACE_TestName = Definition.name
		if Ent.SetName then Ent:SetName(Definition.name) end
	end
	if Definition.stalePhysics then
		ACE.Activate(Ent)
		local Phys = Ent:GetPhysicsObject()
		if IsValid(Phys) then Phys:SetMass(Phys:GetMass() + 1) end
	end
	if Definition.solid == false then
		Ent:SetNotSolid(true)
	end
	if Definition.clipData then Ent.ClipData = Definition.clipData end
	if Definition.activate then
		ACE.Activate(Ent)
	end
	if Definition.uninitialized then
		Ent.ACE = nil
	end

	return Ent
end

local function pointsForceDispatchContract(State, Owner)
	if not (IsValid(Owner) and Owner.CFW_GetContraption and ACE.QueueContraptionPointRebuild
		and ACE.EnsureContraptionPoints) then
		return false
	end

	local Contraption = Owner:CFW_GetContraption()
	if not Contraption and CFW and CFW.createContraption then
		local NewContraption = CFW.createContraption()
		assert(NewContraption, "headless CFW contraption creation failed")
		NewContraption:Add(Owner)
		Contraption = NewContraption
		State.Contraptions = State.Contraptions or {}
		State.Contraptions[#State.Contraptions + 1] = Contraption
	end
	if not Contraption then return false end

	local Count = 0
	local RebuildCount = 0
	local HookName = "ACE_DSL_PointsForce_" .. tostring(Owner:EntIndex())
	local OriginalRebuild = ACE.RebuildContraptionPoints
	hook.Add("ACE_OnContraptionPointsRecalculated", HookName, function(Con)
		if Con == Contraption then Count = Count + 1 end
	end)
	ACE.RebuildContraptionPoints = function(...)
		RebuildCount = RebuildCount + 1
		return OriginalRebuild(...)
	end

	ACE.QueueContraptionPointRebuild(Contraption)
	local Queued = ACE.PendingPointRebuilds and ACE.PendingPointRebuilds[Contraption] == true
	local Ok, Error = pcall(ACE.EnsureContraptionPoints, Contraption, nil, true)
	ACE.RebuildContraptionPoints = OriginalRebuild
	hook.Remove("ACE_OnContraptionPointsRecalculated", HookName)
	if not Ok then error(Error, 0) end

	return Queued and Count == 1 and RebuildCount == 1
end

local function gameplayContract(State, Owner)
	local Result = {}
	local Engine, FuelTank
	local EngineOK, EngineValue = pcall(ACE.MakeEngine, Owner, Vector(-64, 0, 64), Angle(0, 0, 0), "0.8L-I2")
	if EngineOK and IsValid(EngineValue) then
		Engine = track(State, EngineValue)
	end
	local FuelOK, FuelValue = pcall(ACE.MakeFuelTank, Owner, Vector(-96, 0, 64), Angle(0, 0, 0),
		"Tank_4x4x2", "Tank_4x4x2", "Diesel", "Box")
	if FuelOK and IsValid(FuelValue) then
		FuelTank = track(State, FuelValue)
	end
	if IsValid(Engine) and IsValid(FuelTank) then
		FuelTank:TriggerInput("Active", 1)
		local Linked = Engine:Link(FuelTank)
		local Activated = pcall(Engine.TriggerInput, Engine, "Active", 1)
		Result.engine_operation = Linked == true and Activated and Engine.Active == true
	else
		Result.engine_operation = false
	end

	local Ammo, Rack
	local AmmoOK, AmmoValue = pcall(ACE.MakeAmmo, Owner, Vector(32, 0, 64), Angle(0, 0, 0),
		"125:25:25", "BGM-71E ASM", "HEAT", 10, 15, 10, 60, "Wire", "Contact")
	if AmmoOK and IsValid(AmmoValue) then
		Ammo = track(State, AmmoValue)
	end
	local RackOK, RackValue = pcall(ACE.MakeRack, Owner, Vector(0, 0, 64), Angle(0, 0, 0), "1x BGM-71E")
	if RackOK and IsValid(RackValue) then
		Rack = track(State, RackValue)
	end
	if IsValid(Ammo) and IsValid(Rack) then
		local Linked = Rack:Link(Ammo)
		local Copied = pcall(Rack.PreEntityCopy, Rack)
		local Mods = Rack.EntityMods or {}
		Result.rack_link_persistence = Copied and Mods.ACFAmmoLink and Mods.ACFAmmoLink.entities
			and not Mods.ACEAmmoLink
		local Loaded = Rack:AddMissile()
		Result.missile_reload = Linked == true and Loaded == true
			and IsValid(Rack.Missiles[1] and Rack.Missiles[1][1])
			and Rack.Missiles[1][2] == true
	else
		Result.rack_link_persistence = false
		Result.missile_reload = false
	end

	local ChatOK = pcall(ACE.ChatMessageGlobal, "[ACE DSL] chat contract", Color(255, 255, 255))
	Result.chat_surface = ChatOK and util.NetworkStringToID("ACE_ColorChatMessage") > 0
		and file.Exists("ace/client/cl_acemenu_gui.lua", "LUA")
	local LegacyGlobals = {
		{ name = "ACF_GetPhysicalParent", target = "GetPhysicalParent" },
		{ name = "ACF_Kinetic", target = "Kinetic" },
		{ name = "ACF_MuzzleVelocity", target = "MuzzleVelocity" },
		{ name = "ACF_HE", target = "HE" },
		{ name = "ACE_CalculateHERadius", target = "CalculateHERadius" },
		{ name = "ACE_InfraredHeatFromProp", target = "InfraredHeatFromProp" },
		{ name = "ACE_SendNotification", target = "SendNotification" },
		{ name = "ACE_DefineMine", target = "DefineMine" },
		{ name = "ACE_DefineGunFireSound", target = "DefineGunFireSound" }
	}
	local LegacyGlobalsReady = true
	for _, Legacy in ipairs(LegacyGlobals) do
		LegacyGlobalsReady = LegacyGlobalsReady and type(_G[Legacy.name]) == "function"
			and type(ACE[Legacy.target]) == "function"
	end
	Result.weapons_plus_compat = LegacyGlobalsReady and type(ACF) == "table"
		and ACF.PDensity == ACE.PDensity
		and type(ACF_MuzzleVelocity) == "function"
		and type(ACF_Kinetic) == "function"

	local Vehicles = list.GetForEdit("Vehicles")
	local Pod = Vehicles.ACE_pod
	local PilotSeat = Vehicles.ACE_pilotseat
	Result.camera_surface = Vehicles.acf_pod == Pod and Vehicles.acf_pilotseat == PilotSeat
		and Pod and Pod.KeyValues and tostring(Pod.KeyValues.limitview) == "0"
		and PilotSeat and PilotSeat.KeyValues and tostring(PilotSeat.KeyValues.limitview) == "0"
	Result.points_force_dispatch = pointsForceDispatchContract(State, Owner)
	return Result
end

local function damageHookContract(_State, Target)
	local Result = { canonical = 0, legacy = 0 }
	local HookName = "ACE_DSL_DamageHook_" .. tostring(Target:EntIndex())
	local LegacyName = HookName .. "_Legacy"
	hook.Add("ACE_OnDamage", HookName, function()
		Result.canonical = Result.canonical + 1
	end)
	hook.Add("ACEOnDamage", LegacyName, function()
		Result.legacy = Result.legacy + 1
	end)

	local Ok, Error = pcall(ACE.Damage, Target,
		{ Kinetic = 1000, Momentum = 0, Penetration = 1000 }, 3, 0, nil, nil, nil, "AP")
	hook.Remove("ACE_OnDamage", HookName)
	hook.Remove("ACEOnDamage", LegacyName)
	if not Ok then error(Error, 0) end
	return Result
end

local function literal(Value)
	if Value == "true" then return true end
	if Value == "false" then return false end
	local Number = tonumber(Value)
	if Number then return Number end
	local Quoted = Value:match("^\"(.*)\"$")
	return Quoted or Value
end

local function pathValue(State, Path)
	local Root, Rest = Path:match("^([%w_]+)%.(.+)$")
	if not Root then
		if State.DeclaredValues[Path] then return State.Values[Path] end
		if State.DeclaredBindings[Path] then return State.Bindings[Path] end
		return literal(Path)
	end
	local Value = State.Bindings[Root]
	if Value == nil and State.DeclaredValues[Root] then Value = State.Values[Root] end
	for Part in Rest:gmatch("[%w_]+") do
		if Value == nil then return nil end
		Value = Value[Part]
	end
	return Value
end

local function resolveGlobal(Path)
	local Value = _G
	for Part in Path:gmatch("[%w_]+%.?") do
		Part = Part:gsub("%.$", "")
		Value = Value and Value[Part]
	end
	return Value
end

local function action(State, Spec)
	local Args = {}
	for Index, Name in ipairs(Spec.args) do
		Args[Index] = State.Bindings[Name]
	end
	local ArgCount = #Spec.args

	local Function
	if Spec.action == "ACE.CheckLegal" then
		Function = ACE.CheckLegal
	elseif Spec.action == "ACE.GameplayContract" then
		return gameplayContract(State, Args[1])
	elseif Spec.action == "ACE.DamageHookContract" then
		return damageHookContract(State, Args[1])
	else
		Function = resolveGlobal(Spec.path or Spec.action)
		if not isfunction(Function) then error("unknown registered action path: " .. (Spec.path or Spec.action), 0) end
	end

	local Original = ACE.Activate
	State.OriginalActivate = Original
	ACE.Activate = function(...)
		local ActivatedEntity = select(1, ...)
		State.Activations[ActivatedEntity] = (State.Activations[ActivatedEntity] or 0) + 1
		return Original(...)
	end

	local Ok, A, B
	if Spec.action == "ACE.CheckLegal" then
		ACE.Legal.IsActivated = 1
		Ok, A, B = pcall(Function, Args[1], nil, nil, nil, nil, false)
	else
		Ok, A, B = pcall(Function, unpack(Args, 1, ArgCount))
	end

	ACE.Activate = Original
	if not Ok then error(A, 0) end
	if Spec.action == "ACE.CheckLegal" then
		if istable(A) then
			local Problems = A.Problems or {}
			return { legal = A.Legal == true, reason = table.concat(Problems, ", ") }
		end
		return { legal = A, reason = B }
	end
	return A
end

local function expectCase(State, Spec, Expect)
	for Index, Check in ipairs(Spec.expects) do
		local Subject = Check.subject
		local Value
		local Ok, AssertionError = pcall(function()
			if Check.operator == "was reactivated" or Check.operator == "was activated" then
				Value = (State.Activations[State.Bindings[Subject]] or 0) > 0
			elseif Check.operator == "has armor and health" then
				local ACEState = pathValue(State, Subject)
				Value = ACEState and ACEState.Armour ~= nil and ACEState.Health ~= nil
			elseif Check.operator == "reason is" then
				Value = State.Values[Subject].reason
			else
				Value = pathValue(State, Subject)
			end

			if Check.operator == "exists" then
				Expect(Value).to.exist()
			elseif Check.operator == "does not exist" then
				Expect(Value).notTo.exist()
			elseif Check.operator == "is greater than" then
				Expect(Value).to.beGreaterThan(pathValue(State, Check.value))
			elseif Check.operator == "is less than" then
				Expect(Value).to.beLessThan(pathValue(State, Check.value))
			elseif Check.operator == "was reactivated" or Check.operator == "was activated" or Check.operator == "has armor and health" then
				Expect(Value).to.beTrue()
			elseif Check.operator == "is legal" then
				Expect(Value.legal).to.beTrue()
			elseif Check.operator == "is not legal" then
				Expect(Value.legal).to.beFalse()
			else
				Expect(Value).to.equal(literal(Check.value))
			end
		end)

		if not Ok then
			local Expected = Check.value ~= nil and Check.value ~= "" and " " .. tostring(Check.value) or ""
			error(string.format(
				"ACE DSL scenario %s expectation %d failed: expect %s %s%s (actual %s): %s",
				tostring(Spec.scenarioId), Index, Subject, Check.operator, Expected,
				tostring(Value), tostring(AssertionError)
			))
		end
	end
end

function Runtime.Run(State, Spec, Expect)
	for _, Item in ipairs(Spec.actions or {}) do
		if Item.path == "ACE.GameplayContract" then
			ensureHeadlessOwnership(State)
			break
		end
	end
	State.Entities = {}
	State.Contraptions = {}
	State.MethodOverrides = {}
	State.MethodOriginals = {}
	State.MethodInstalled = {}
	State.Bindings = {}
	State.DeclaredBindings = {}
	State.Values = {}
	State.DeclaredValues = {}
	State.Activations = {}
	State.OriginalLegalActivated = ACE.Legal and ACE.Legal.IsActivated
	State.OriginalLegalActivatedCaptured = ACE.Legal ~= nil
	State.OriginalActivate = ACE.Activate
	State.FixtureDefinitions = Spec.fixturesRegistry or {}

	local Ok, Error = xpcall(function()
		for _, Item in ipairs(Spec.fixtures) do
			State.DeclaredBindings[Item.alias] = true
			State.Bindings[Item.alias] = fixture(State, Item.fixture, State.FixtureDefinitions)
		end

		for _, Item in ipairs(Spec.actions) do
			State.DeclaredValues[Item.result] = true
			State.Values[Item.result] = action(State, Item)
		end

		expectCase(State, Spec, Expect)
	end, function(Message)
		return debug.traceback(Message, 2)
	end)
	if not Ok then
		local CleanupOK, CleanupError = pcall(Runtime.Cleanup, State)
		if not CleanupOK then
			error(tostring(Error) .. "\n" .. tostring(CleanupError), 0)
		end
		error(Error, 0)
	end
end

function Runtime.Cleanup(State)
	if State.OriginalActivate ~= nil then ACE.Activate = State.OriginalActivate end
	if ACE.Legal and State.OriginalLegalActivatedCaptured then
		ACE.Legal.IsActivated = State.OriginalLegalActivated
	end
	local Meta = FindMetaTable("Entity")
	for Name, Original in pairs(State.MethodOriginals or {}) do
		Meta[Name] = Original
	end
	local CleanupError
	local Remaining = {}
	for Index = #(State.Entities or {}), 1, -1 do
		local Ent = State.Entities[Index]
		if IsValid(Ent) then
			local Ok, Error = pcall(function() Ent:Remove() end)
			if not Ok then
				Remaining[#Remaining + 1] = Ent
				CleanupError = CleanupError or Error
			end
		end
	end
	State.Entities = Remaining
	for Index = #(State.Contraptions or {}), 1, -1 do
		local Contraption = State.Contraptions[Index]
		if Contraption and Contraption.Remove and not Contraption._removed then
			local Ok, Error = pcall(Contraption.Remove, Contraption)
			if not Ok then CleanupError = CleanupError or Error end
		end
	end
	State.Contraptions = {}
	restoreHeadlessOwnership(State)
	if CleanupError then error("ACE DSL cleanup failed: " .. tostring(CleanupError), 0) end
end

return Runtime
