-- Runtime for generated ACE .ace_test groups.
-- Maintainers do not edit this file; it owns native fixture creation, actions, observations,
-- assertions, and cleanup underneath the maintainer-facing DSL.

local Runtime = {}

local function overrideMethod(State, Ent, Name, Callback)
	local Meta = FindMetaTable("Entity")
	State.MethodOverrides[Name] = State.MethodOverrides[Name] or {}
	State.MethodOriginals[Name] = State.MethodOriginals[Name] or Meta[Name]
	State.MethodOverrides[Name][Ent] = Callback
	if State.MethodInstalled[Name] then return end
	local Original = State.MethodOriginals[Name]
	Meta[Name] = function(self, ...)
		local Override = State.MethodOverrides[Name][self]
		if Override then return Override(self, ...) end
		return Original(self, ...)
	end
	State.MethodInstalled[Name] = true
end

local function track(State, Ent)
	if IsValid(Ent) then
		State.Entities[#State.Entities + 1] = Ent
	end
	return Ent
end

local function fixture(State, Name, Definitions)
	local Definition = Definitions and Definitions[Name]
	if not Definition or Definition.invalid then return nil end

	local Ent
	local SpawnClass = Definition.spawnClass or Definition.class or "prop_physics"
	if Definition.physics == "invalid" then
		Ent = track(State, ents.Create(SpawnClass))
		if not IsValid(Ent) then return end
		Ent:SetModel(Definition.model or "models/props_junk/wood_crate001a.mdl")
	else
		Ent = track(State, ents.Create(SpawnClass))
		if not IsValid(Ent) then return end
		Ent:SetModel(Definition.model or "models/props_junk/wood_crate001a.mdl")
		Ent:Spawn()
	end
	if not Ent then return end
	if Ent.Activate then Ent:Activate() end
	local Phys = Ent:GetPhysicsObject()
	if IsValid(Phys) then
		if Phys.SetMass then Phys:SetMass(Definition.mass or 10) end
		if Phys.Wake then Phys:Wake() end
	end

	if Definition.kind == "native_player" then
		overrideMethod(State, Ent, "IsPlayer", function() return true end)
	elseif Definition.kind == "native_vehicle" then
		overrideMethod(State, Ent, "IsVehicle", function() return true end)
	end
	if Definition.class and Definition.class ~= "prop_physics" then
		local Class = Definition.class
		overrideMethod(State, Ent, "GetClass", function() return Class end)
	end
	if Definition.ignoredClass then
		local Class = Definition.ignoredClass
		overrideMethod(State, Ent, "GetClass", function() return Class end)
	end
	if Definition.exploding then Ent.Exploding = true end
	if Definition.ace then
		Ent.ACE = Ent.ACE or {}
		for Key, Value in pairs(Definition.ace) do Ent.ACE[Key] = Value end
	end
	if Definition.name then
		Ent.ACE_TestName = Definition.name
		if Ent.SetName then Ent:SetName(Definition.name) end
	end
	if Definition.stalePhysics then
		ACE.Activate(Ent)
		local Phys = Ent:GetPhysicsObject()
		if IsValid(Phys) then Phys:SetMass(Phys:GetMass() + 1) end
	end
	if Definition.solid == false then
		Ent:SetNotSolid(true)
	end
	if Definition.clipData then Ent.ClipData = Definition.clipData end
	if Definition.activate then
		ACE.Activate(Ent)
	end
	if Definition.uninitialized then
		Ent.ACE = nil
	end

	return Ent
end

local function literal(Value)
	if Value == "true" then return true end
	if Value == "false" then return false end
	local Number = tonumber(Value)
	if Number then return Number end
	local Quoted = Value:match("^\"(.*)\"$")
	return Quoted or Value
end

local function pathValue(State, Path)
	local Root, Rest = Path:match("^([%w_]+)%.(.+)$")
	if not Root then
		if State.DeclaredValues[Path] then return State.Values[Path] end
		if State.DeclaredBindings[Path] then return State.Bindings[Path] end
		return literal(Path)
	end
	local Value = State.Bindings[Root]
	if Value == nil and State.DeclaredValues[Root] then Value = State.Values[Root] end
	for Part in Rest:gmatch("[%w_]+") do
		if Value == nil then return nil end
		Value = Value[Part]
	end
	return Value
end

local function resolveGlobal(Path)
	local Value = _G
	for Part in Path:gmatch("[%w_]+%.?") do
		Part = Part:gsub("%.$", "")
		Value = Value and Value[Part]
	end
	return Value
end

local function action(State, Spec)
	local Args = {}
	for Index, Name in ipairs(Spec.args) do
		Args[Index] = State.Bindings[Name]
	end
	local ArgCount = #Spec.args

	local Function
	if Spec.action == "ACE.CheckLegal" then
		Function = ACE.CheckLegal
	else
		Function = resolveGlobal(Spec.path or Spec.action)
		if not isfunction(Function) then error("unknown registered action path: " .. (Spec.path or Spec.action), 0) end
	end

	local Original = ACE.Activate
	State.OriginalActivate = Original
	ACE.Activate = function(...)
		local ActivatedEntity = select(1, ...)
		State.Activations[ActivatedEntity] = (State.Activations[ActivatedEntity] or 0) + 1
		return Original(...)
	end

	local Ok, A, B
	if Spec.action == "ACE.CheckLegal" then
		ACE.Legal.IsActivated = 1
		Ok, A, B = pcall(Function, Args[1], nil, nil, nil, nil, false)
	else
		Ok, A, B = pcall(Function, unpack(Args, 1, ArgCount))
	end

	ACE.Activate = Original
	if not Ok then error(A, 0) end
	if Spec.action == "ACE.CheckLegal" then
		if istable(A) then
			local Problems = A.Problems or {}
			return { legal = A.Legal == true, reason = table.concat(Problems, ", ") }
		end
		return { legal = A, reason = B }
	end
	return A
end

local function expectCase(State, Spec, Expect)
	for _, Check in ipairs(Spec.expects) do
		local Subject = Check.subject
		local Value
		if Check.operator == "was reactivated" or Check.operator == "was activated" then
			Value = (State.Activations[State.Bindings[Subject]] or 0) > 0
		elseif Check.operator == "has armor and health" then
			local ACEState = pathValue(State, Subject)
			Value = ACEState and ACEState.Armour ~= nil and ACEState.Health ~= nil
		elseif Check.operator == "reason is" then
			Value = State.Values[Subject].reason
		else
			Value = pathValue(State, Subject)
		end

		if Check.operator == "exists" then
			Expect(Value).to.exist()
		elseif Check.operator == "does not exist" then
			Expect(Value).notTo.exist()
		elseif Check.operator == "is greater than" then
			Expect(Value).to.beGreaterThan(pathValue(State, Check.value))
		elseif Check.operator == "is less than" then
			Expect(Value).to.beLessThan(pathValue(State, Check.value))
		elseif Check.operator == "was reactivated" or Check.operator == "was activated" or Check.operator == "has armor and health" then
			Expect(Value).to.beTrue()
		elseif Check.operator == "is legal" then
			Expect(Value.legal).to.beTrue()
		elseif Check.operator == "is not legal" then
			Expect(Value.legal).to.beFalse()
		elseif Check.operator == "reason is" then
			Expect(Value).to.equal(literal(Check.value))
		else
			Expect(Value).to.equal(literal(Check.value))
		end
	end
end

function Runtime.Run(State, Spec, Expect)
	State.Entities = {}
	State.MethodOverrides = {}
	State.MethodOriginals = {}
	State.MethodInstalled = {}
	State.Bindings = {}
	State.DeclaredBindings = {}
	State.Values = {}
	State.DeclaredValues = {}
	State.Activations = {}
	State.OriginalLegalActivated = ACE.Legal and ACE.Legal.IsActivated
	State.OriginalLegalActivatedCaptured = ACE.Legal ~= nil
	State.OriginalActivate = ACE.Activate
	State.FixtureDefinitions = Spec.fixturesRegistry or {}

	for _, Item in ipairs(Spec.fixtures) do
		State.DeclaredBindings[Item.alias] = true
		State.Bindings[Item.alias] = fixture(State, Item.fixture, State.FixtureDefinitions)
	end

	for _, Item in ipairs(Spec.actions) do
		State.DeclaredValues[Item.result] = true
		State.Values[Item.result] = action(State, Item)
	end

	expectCase(State, Spec, Expect)
end

function Runtime.Cleanup(State)
	if State.OriginalActivate ~= nil then ACE.Activate = State.OriginalActivate end
	if ACE.Legal and State.OriginalLegalActivatedCaptured then
		ACE.Legal.IsActivated = State.OriginalLegalActivated
	end
	local Meta = FindMetaTable("Entity")
	for Name, Original in pairs(State.MethodOriginals or {}) do
		Meta[Name] = Original
	end
	local Remaining = {}
	local CleanupError
	for Index = #(State.Entities or {}), 1, -1 do
		local Ent = State.Entities[Index]
		if IsValid(Ent) then
			local Ok, Error = pcall(function() Ent:Remove() end)
			if not Ok then
				Remaining[#Remaining + 1] = Ent
				CleanupError = CleanupError or Error
			end
		end
	end
	State.Entities = Remaining
	if CleanupError then error("ACE DSL cleanup failed: " .. tostring(CleanupError), 0) end
end

return Runtime
