ENT.Type = "anim"
ENT.Base = "ace_aps"
ENT.PrintName = "ACE Zaslin APS"
ENT.WireDebugName = "ACE Zaslin APS"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.APSVariant = "zaslin"
ENT.APSPreset = "Zaslin"
ENT.APSModel = "models/golem/Zaslin_APS.mdl"
ENT.Charges = ACE.APSPresets.Zaslin.Charges
ENT.KillRange = ACE.APSPresets.Zaslin.KillRange
ENT.ReloadTime = ACE.APSPresets.Zaslin.ReloadTime
ENT.RadarSize = ACE.APSPresets.Zaslin.RadarSize
ENT.YawCoverage = ACE.APSPresets.Zaslin.YawCoverage
ENT.PitchCoverage = ACE.APSPresets.Zaslin.PitchCoverage
ENT.GunMountOffset = Vector(0, 28, 0)
ENT.GunMountAngle = Angle(0, 90, 0)
ENT.TubeBodygroup = 0
ENT.TubeLoadedSubmodel = 1
ENT.TubeEmptySubmodel = 0
