ENT.Type = "anim"
ENT.Base = "ace_aps"
ENT.PrintName = "ACE APS (Static)"
ENT.WireDebugName = "ACE APS Static"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.APSVariant = "static"
ENT.APSModel = "models/golem/Zaslin_APS.mdl"
ENT.GunMountOffset = Vector(0, 28, 0)
ENT.GunMountAngle = Angle(0, 90, 0)
