ENT.Type = "anim"
ENT.Base = "ace_aps"
ENT.PrintName = "ACE APS (Gimbal)"
ENT.WireDebugName = "ACE APS Gimbal"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.APSVariant = "gimbal"
ENT.APSModel = "models/props_lab/reciever01a.mdl"
ENT.Charges = 1
ENT.KillRange = 3
ENT.YawRadius = 90
ENT.PitchRadius = 45
ENT.SlewRate = 180
ENT.AimCone = 2
